// If you want to undef all external users macros
// you should include given file only after library files
// clean up
#undef SERIALIZATION_LOAD
#undef SERIALIZATION_SAVE
#undef SERIALIZATION_UNIFIED

#undef SERIALIZATION_ACCESS

#undef SERIALIZATION_LOAD_DATA
#undef SERIALIZATION_SAVE_DATA
#undef SERIALIZATION_UNIFIED_DATA

#undef SERIALIZATION_CLASS_INFO
#undef SERIALIZATION_CLASS_HASH_INFO
#undef SERIALIZATION_CLASS_EXPORT

#undef SERIALIZATION_CLASS_TPL_INFO
#undef SERIALIZATION_CLASS_TPL_HASH_INFO
#undef SERIALIZATION_CLASS_TPL_EXPORT

#undef SERIALIZATION_TYPE_REGISTRY
#undef SERIALIZATION_TYPE_REGISTRY_IF
