// If you want to undef all external users macros
// you should include given file only after library files
// clean up
#undef SERIALIZATION_LOAD
#undef SERIALIZATION_SAVE
#undef SERIALIZATION_UNIFIED

#undef SERIALIZATION_HAS_FUNCTION_TPL_HELPER

#undef SERIALIZATION_ARCHIVE_ACCESS

#undef SERIALIZATION_ARCHIVE_TPL_DECLARATION

#undef SERIALIZATION_READ_ARCHIVE_GENERIC
#undef SERIALIZATION_WRITE_ARCHIVE_GENERIC
