// If you want to undef all external lib's macros
// you should include given file only after library files

// clean up
#undef SERIALIZABLE_ACCESS

#undef EXPORT_SERIALIZABLE_ARCHIVE

#undef INSTANTIABLE_TYPE
#undef INSTANTIABLE_VOID_POINTER_TYPES

#undef INSTANTIABLE_KEY
#undef INSTANTIABLE

#undef SERIALIZABLE
#undef TEMPLATE_SERIALIZABLE
#undef CONDITIONAL_SERIALIZABLE
#undef SERIALIZABLE_DECLARATION
#undef SERIALIZABLE_DEFINITION

#undef BITPACK

#undef SF_STRING_HASH
#undef SF_TYPE_HASH
#undef SF_EXPRESSION_HASH

#undef SF_ARCHIVE_TRAIT_MAX_KEY_SIZE
#undef SF_BYTE_STREAM_RESERVE_SIZE

// possible to undef
// #undef SF_PTRTRACK_DISABLE
// #undef SF_DEFAULT_DISABLE
// #undef SF_TYPE_PORTABLE_DISABLE
// #undef SF_ANY_SUPPORT_DISABLE
// #undef SF_GARBAGE_CHECK_DISABLE

#undef SF_REQUIRES
