#ifndef SF_DYNAMIC_INSTANTIABLE_TRAITS_HPP
#define SF_DYNAMIC_INSTANTIABLE_TRAITS_HPP

#include <SF/Core/Hash.hpp>

#define INSTANTIABLE(...) \
        static inline bool autogenerated = ::sf::dynamic::instantiable_registry.fixture<__VA_ARGS__>();

#define INSTANTIABLE_KEY(instantiable_key, ...) \
        static ::xxsf_instantiable_traits_key_type key() { return instantiable_key; } \
        INSTANTIABLE(__VA_ARGS__)

using xxsf_instantiable_traits_key_type = std::uint64_t;
static constexpr auto xxsf_instantiable_traits_base_key = xxsf_instantiable_traits_key_type(-1);

#endif // SF_DYNAMIC_INSTANTIABLE_TRAITS_HPP
