#ifndef EIGHTSER_DETAIL_PREPROCESSOR_HPP
#define EIGHTSER_DETAIL_PREPROCESSOR_HPP

// concatenation of two macro arguments
#define EIGHTSER_CONCAT(lhs, rhs) EIGHTSER_CONCAT_IMPL(lhs, rhs)
#define EIGHTSER_CONCAT_IMPL(lhs, rhs) EIGHTSER_CONCAT_IMPL_(lhs, rhs)
#define EIGHTSER_CONCAT_IMPL_(lhs, rhs) lhs##rhs

// deparen of macro argument
#define EIGHTSER_DEPAREN(arg) EIGHTSER_DEPAREN_IMPL(EIGHTSER_UATE arg)
#define EIGHTSER_UATE(...) EIGHTSER_UATE __VA_ARGS__
#define EIGHTSER_DEPAREN_IMPL(...) EIGHTSER_DEPAREN_IMPL_(__VA_ARGS__)
#define EIGHTSER_DEPAREN_IMPL_(...) EIGHTSER_EVAL ## __VA_ARGS__
#define EIGHTSER_EVALEIGHTSER_UATE

// return first argument from two
#define EIGHTSER_FIRST_ARGUMENT(first, ...) first

#define EIGHTSER_VA_ARGS_SIZE_IMPL_( \
     _1,  _2,  _3,  _4,  _5,  _6,  _7,  _8,  _9, _10, _11, _12, _13, _14, _15, _16, \
    _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, \
    _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, \
    _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, _61, _62, _63, N, ...) N

#define EIGHTSER_REVERSE_INTEGER_SEQUENCE \
    63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, \
    47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, \
    31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, \
    15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0

#define EIGHTSER_VA_ARGS_SIZE_IMPL(...) EIGHTSER_VA_ARGS_SIZE_IMPL_(__VA_ARGS__)

// return __VA_ARGS__ arguments count, for empty __VA_ARGS__ return 1
#define EIGHTSER_VA_ARGS_SIZE(...) EIGHTSER_VA_ARGS_SIZE_IMPL(__VA_ARGS__, EIGHTSER_REVERSE_INTEGER_SEQUENCE)

// generate repeat sequence macro(1) macro(2) ... macro(count)
#define EIGHTSER_REPEAT(macro, count) EIGHTSER_CONCAT(EIGHTSER_REPEAT_, count)(macro)

#define EIGHTSER_REPEAT_0(macro)

#define EIGHTSER_REPEAT_1(macro) EIGHTSER_REPEAT_0(macro) macro(1)
#define EIGHTSER_REPEAT_2(macro) EIGHTSER_REPEAT_1(macro) macro(2)
#define EIGHTSER_REPEAT_3(macro) EIGHTSER_REPEAT_2(macro) macro(3)
#define EIGHTSER_REPEAT_4(macro) EIGHTSER_REPEAT_3(macro) macro(4)
#define EIGHTSER_REPEAT_5(macro) EIGHTSER_REPEAT_4(macro) macro(5)
#define EIGHTSER_REPEAT_6(macro) EIGHTSER_REPEAT_5(macro) macro(6)
#define EIGHTSER_REPEAT_7(macro) EIGHTSER_REPEAT_6(macro) macro(7)
#define EIGHTSER_REPEAT_8(macro) EIGHTSER_REPEAT_7(macro) macro(8)

#define EIGHTSER_REPEAT_9(macro) EIGHTSER_REPEAT_8(macro) macro(9)
#define EIGHTSER_REPEAT_10(macro) EIGHTSER_REPEAT_9(macro) macro(10)
#define EIGHTSER_REPEAT_11(macro) EIGHTSER_REPEAT_10(macro) macro(11)
#define EIGHTSER_REPEAT_12(macro) EIGHTSER_REPEAT_11(macro) macro(12)
#define EIGHTSER_REPEAT_13(macro) EIGHTSER_REPEAT_12(macro) macro(13)
#define EIGHTSER_REPEAT_14(macro) EIGHTSER_REPEAT_13(macro) macro(14)
#define EIGHTSER_REPEAT_15(macro) EIGHTSER_REPEAT_14(macro) macro(15)
#define EIGHTSER_REPEAT_16(macro) EIGHTSER_REPEAT_15(macro) macro(16)

#define EIGHTSER_REPEAT_17(macro) EIGHTSER_REPEAT_16(macro) macro(17)
#define EIGHTSER_REPEAT_18(macro) EIGHTSER_REPEAT_17(macro) macro(18)
#define EIGHTSER_REPEAT_19(macro) EIGHTSER_REPEAT_18(macro) macro(19)
#define EIGHTSER_REPEAT_20(macro) EIGHTSER_REPEAT_19(macro) macro(20)
#define EIGHTSER_REPEAT_21(macro) EIGHTSER_REPEAT_20(macro) macro(21)
#define EIGHTSER_REPEAT_22(macro) EIGHTSER_REPEAT_21(macro) macro(22)
#define EIGHTSER_REPEAT_23(macro) EIGHTSER_REPEAT_22(macro) macro(23)
#define EIGHTSER_REPEAT_24(macro) EIGHTSER_REPEAT_23(macro) macro(24)

#define EIGHTSER_REPEAT_25(macro) EIGHTSER_REPEAT_24(macro) macro(25)
#define EIGHTSER_REPEAT_26(macro) EIGHTSER_REPEAT_25(macro) macro(26)
#define EIGHTSER_REPEAT_27(macro) EIGHTSER_REPEAT_26(macro) macro(27)
#define EIGHTSER_REPEAT_28(macro) EIGHTSER_REPEAT_27(macro) macro(28)
#define EIGHTSER_REPEAT_29(macro) EIGHTSER_REPEAT_28(macro) macro(29)
#define EIGHTSER_REPEAT_30(macro) EIGHTSER_REPEAT_29(macro) macro(30)
#define EIGHTSER_REPEAT_31(macro) EIGHTSER_REPEAT_30(macro) macro(31)
#define EIGHTSER_REPEAT_32(macro) EIGHTSER_REPEAT_31(macro) macro(32)

#define EIGHTSER_REPEAT_33(macro) EIGHTSER_REPEAT_32(macro) macro(33)
#define EIGHTSER_REPEAT_34(macro) EIGHTSER_REPEAT_33(macro) macro(34)
#define EIGHTSER_REPEAT_35(macro) EIGHTSER_REPEAT_34(macro) macro(35)
#define EIGHTSER_REPEAT_36(macro) EIGHTSER_REPEAT_35(macro) macro(36)
#define EIGHTSER_REPEAT_37(macro) EIGHTSER_REPEAT_36(macro) macro(37)
#define EIGHTSER_REPEAT_38(macro) EIGHTSER_REPEAT_37(macro) macro(38)
#define EIGHTSER_REPEAT_39(macro) EIGHTSER_REPEAT_38(macro) macro(39)
#define EIGHTSER_REPEAT_40(macro) EIGHTSER_REPEAT_39(macro) macro(40)

#define EIGHTSER_REPEAT_41(macro) EIGHTSER_REPEAT_40(macro) macro(41)
#define EIGHTSER_REPEAT_42(macro) EIGHTSER_REPEAT_41(macro) macro(42)
#define EIGHTSER_REPEAT_43(macro) EIGHTSER_REPEAT_42(macro) macro(43)
#define EIGHTSER_REPEAT_44(macro) EIGHTSER_REPEAT_43(macro) macro(44)
#define EIGHTSER_REPEAT_45(macro) EIGHTSER_REPEAT_44(macro) macro(45)
#define EIGHTSER_REPEAT_46(macro) EIGHTSER_REPEAT_45(macro) macro(46)
#define EIGHTSER_REPEAT_47(macro) EIGHTSER_REPEAT_46(macro) macro(47)
#define EIGHTSER_REPEAT_48(macro) EIGHTSER_REPEAT_47(macro) macro(48)

#define EIGHTSER_REPEAT_49(macro) EIGHTSER_REPEAT_48(macro) macro(49)
#define EIGHTSER_REPEAT_50(macro) EIGHTSER_REPEAT_49(macro) macro(50)
#define EIGHTSER_REPEAT_51(macro) EIGHTSER_REPEAT_50(macro) macro(51)
#define EIGHTSER_REPEAT_52(macro) EIGHTSER_REPEAT_51(macro) macro(52)
#define EIGHTSER_REPEAT_53(macro) EIGHTSER_REPEAT_52(macro) macro(53)
#define EIGHTSER_REPEAT_54(macro) EIGHTSER_REPEAT_53(macro) macro(54)
#define EIGHTSER_REPEAT_55(macro) EIGHTSER_REPEAT_54(macro) macro(55)
#define EIGHTSER_REPEAT_56(macro) EIGHTSER_REPEAT_55(macro) macro(56)

#define EIGHTSER_REPEAT_57(macro) EIGHTSER_REPEAT_56(macro) macro(57)
#define EIGHTSER_REPEAT_58(macro) EIGHTSER_REPEAT_57(macro) macro(58)
#define EIGHTSER_REPEAT_59(macro) EIGHTSER_REPEAT_58(macro) macro(59)
#define EIGHTSER_REPEAT_60(macro) EIGHTSER_REPEAT_59(macro) macro(60)
#define EIGHTSER_REPEAT_61(macro) EIGHTSER_REPEAT_60(macro) macro(61)
#define EIGHTSER_REPEAT_62(macro) EIGHTSER_REPEAT_61(macro) macro(62)
#define EIGHTSER_REPEAT_63(macro) EIGHTSER_REPEAT_62(macro) macro(63)
#define EIGHTSER_REPEAT_64(macro) EIGHTSER_REPEAT_63(macro) macro(64)
// and etc.

// generate placeholder sequence _0, _1, _2, ..., _count
#define EIGHTSER_PLACEHOLDERS(count) EIGHTSER_CONCAT(EIGHTSER_PLACEHOLDER_, count)()

#define EIGHTSER_PLACEHOLDER_1() _0
#define EIGHTSER_PLACEHOLDER_2() EIGHTSER_PLACEHOLDER_1(), _1
#define EIGHTSER_PLACEHOLDER_3() EIGHTSER_PLACEHOLDER_2(), _2
#define EIGHTSER_PLACEHOLDER_4() EIGHTSER_PLACEHOLDER_3(), _3
#define EIGHTSER_PLACEHOLDER_5() EIGHTSER_PLACEHOLDER_4(), _4
#define EIGHTSER_PLACEHOLDER_6() EIGHTSER_PLACEHOLDER_5(), _5
#define EIGHTSER_PLACEHOLDER_7() EIGHTSER_PLACEHOLDER_6(), _6
#define EIGHTSER_PLACEHOLDER_8() EIGHTSER_PLACEHOLDER_7(), _7

#define EIGHTSER_PLACEHOLDER_9() EIGHTSER_PLACEHOLDER_8(), _8
#define EIGHTSER_PLACEHOLDER_10() EIGHTSER_PLACEHOLDER_9(), _9
#define EIGHTSER_PLACEHOLDER_11() EIGHTSER_PLACEHOLDER_10(), _10
#define EIGHTSER_PLACEHOLDER_12() EIGHTSER_PLACEHOLDER_11(), _11
#define EIGHTSER_PLACEHOLDER_13() EIGHTSER_PLACEHOLDER_12(), _12
#define EIGHTSER_PLACEHOLDER_14() EIGHTSER_PLACEHOLDER_13(), _13
#define EIGHTSER_PLACEHOLDER_15() EIGHTSER_PLACEHOLDER_14(), _14
#define EIGHTSER_PLACEHOLDER_16() EIGHTSER_PLACEHOLDER_15(), _15

#define EIGHTSER_PLACEHOLDER_17() EIGHTSER_PLACEHOLDER_16(), _16
#define EIGHTSER_PLACEHOLDER_18() EIGHTSER_PLACEHOLDER_17(), _17
#define EIGHTSER_PLACEHOLDER_19() EIGHTSER_PLACEHOLDER_18(), _18
#define EIGHTSER_PLACEHOLDER_20() EIGHTSER_PLACEHOLDER_19(), _19
#define EIGHTSER_PLACEHOLDER_21() EIGHTSER_PLACEHOLDER_20(), _20
#define EIGHTSER_PLACEHOLDER_22() EIGHTSER_PLACEHOLDER_21(), _21
#define EIGHTSER_PLACEHOLDER_23() EIGHTSER_PLACEHOLDER_22(), _22
#define EIGHTSER_PLACEHOLDER_24() EIGHTSER_PLACEHOLDER_23(), _23

#define EIGHTSER_PLACEHOLDER_25() EIGHTSER_PLACEHOLDER_24(), _24
#define EIGHTSER_PLACEHOLDER_26() EIGHTSER_PLACEHOLDER_25(), _25
#define EIGHTSER_PLACEHOLDER_27() EIGHTSER_PLACEHOLDER_26(), _26
#define EIGHTSER_PLACEHOLDER_28() EIGHTSER_PLACEHOLDER_27(), _27
#define EIGHTSER_PLACEHOLDER_29() EIGHTSER_PLACEHOLDER_28(), _28
#define EIGHTSER_PLACEHOLDER_30() EIGHTSER_PLACEHOLDER_29(), _29
#define EIGHTSER_PLACEHOLDER_31() EIGHTSER_PLACEHOLDER_30(), _30
#define EIGHTSER_PLACEHOLDER_32() EIGHTSER_PLACEHOLDER_31(), _31

#define EIGHTSER_PLACEHOLDER_33() EIGHTSER_PLACEHOLDER_32(), _32
#define EIGHTSER_PLACEHOLDER_34() EIGHTSER_PLACEHOLDER_33(), _33
#define EIGHTSER_PLACEHOLDER_35() EIGHTSER_PLACEHOLDER_34(), _34
#define EIGHTSER_PLACEHOLDER_36() EIGHTSER_PLACEHOLDER_35(), _35
#define EIGHTSER_PLACEHOLDER_37() EIGHTSER_PLACEHOLDER_36(), _36
#define EIGHTSER_PLACEHOLDER_38() EIGHTSER_PLACEHOLDER_37(), _37
#define EIGHTSER_PLACEHOLDER_39() EIGHTSER_PLACEHOLDER_38(), _38
#define EIGHTSER_PLACEHOLDER_40() EIGHTSER_PLACEHOLDER_39(), _39

#define EIGHTSER_PLACEHOLDER_41() EIGHTSER_PLACEHOLDER_40(), _40
#define EIGHTSER_PLACEHOLDER_42() EIGHTSER_PLACEHOLDER_41(), _41
#define EIGHTSER_PLACEHOLDER_43() EIGHTSER_PLACEHOLDER_42(), _42
#define EIGHTSER_PLACEHOLDER_44() EIGHTSER_PLACEHOLDER_43(), _43
#define EIGHTSER_PLACEHOLDER_45() EIGHTSER_PLACEHOLDER_44(), _44
#define EIGHTSER_PLACEHOLDER_46() EIGHTSER_PLACEHOLDER_45(), _45
#define EIGHTSER_PLACEHOLDER_47() EIGHTSER_PLACEHOLDER_46(), _46
#define EIGHTSER_PLACEHOLDER_48() EIGHTSER_PLACEHOLDER_47(), _47

#define EIGHTSER_PLACEHOLDER_49() EIGHTSER_PLACEHOLDER_48(), _48
#define EIGHTSER_PLACEHOLDER_50() EIGHTSER_PLACEHOLDER_49(), _49
#define EIGHTSER_PLACEHOLDER_51() EIGHTSER_PLACEHOLDER_50(), _50
#define EIGHTSER_PLACEHOLDER_52() EIGHTSER_PLACEHOLDER_51(), _51
#define EIGHTSER_PLACEHOLDER_53() EIGHTSER_PLACEHOLDER_52(), _52
#define EIGHTSER_PLACEHOLDER_54() EIGHTSER_PLACEHOLDER_53(), _53
#define EIGHTSER_PLACEHOLDER_55() EIGHTSER_PLACEHOLDER_54(), _54
#define EIGHTSER_PLACEHOLDER_56() EIGHTSER_PLACEHOLDER_55(), _55

#define EIGHTSER_PLACEHOLDER_57() EIGHTSER_PLACEHOLDER_56(), _56
#define EIGHTSER_PLACEHOLDER_58() EIGHTSER_PLACEHOLDER_57(), _57
#define EIGHTSER_PLACEHOLDER_59() EIGHTSER_PLACEHOLDER_58(), _58
#define EIGHTSER_PLACEHOLDER_60() EIGHTSER_PLACEHOLDER_59(), _59
#define EIGHTSER_PLACEHOLDER_61() EIGHTSER_PLACEHOLDER_60(), _60
#define EIGHTSER_PLACEHOLDER_62() EIGHTSER_PLACEHOLDER_61(), _61
#define EIGHTSER_PLACEHOLDER_63() EIGHTSER_PLACEHOLDER_62(), _62
#define EIGHTSER_PLACEHOLDER_64() EIGHTSER_PLACEHOLDER_63(), _63
// and etc.

#endif // EIGHTSER_DETAIL_PREPROCESSOR_HPP
