// If you want to undef all external lib's macros
// you should include given file only after library files

// clean up
#undef SERIALIZATION_ACCESS

#undef EXPORT_SERIALIZATION_ARCHIVE

#undef INSTANTIABLE_TYPE
#undef SERIALIZATION_FIXTURE
#undef SERIALIZATION_TRAITS

#undef EXPORT_INSTANTIABLE_KEY
#undef EXPORT_INSTANTIABLE

#undef SERIALIZATION
#undef TEMPLATE_SERIALIZATION
#undef CONDITIONAL_SERIALIZATION
#undef SERIALIZATION_DECLARATION
#undef SERIALIZATION_DEFINITION

#undef BITPACK

#undef SF_STATIC_HASH
#undef SF_STATIC_HASH_KEY_TYPE
#undef SF_TYPE_HASH

#undef SF_ARCHIVE_TRAIT_MAX_KEY_SIZE
#undef SF_BYTE_STREAM_RESERVE_SIZE

// possible to undef
// #undef SF_PTRTRACK_DISABLE
// #undef SF_DEFAULT_DISABLE
// #undef SF_TYPE_PORTABLE_DISABLE
// #undef SF_EXTERN_RUNTIME_TRAIT
// #undef SF_EXTERN_TRAIT
// #undef SF_EXPORT_INSTANTIABLE_DISABLE
// #undef SF_ANY_SUPPORT_DISABLE
// #undef SF_REGISTRY_ACCESS
// #undef SF_GARBAGE_CHECK_DISABLE

#undef SF_REQUIRE
