// If you want to undef all external users macros
// you should include given file only after library files
// note that: MACRO - is public macro, _MACRO - is private

// clean up
#undef SERIALIZATION_ACCESS

#undef SERIALIZATION_LOAD_DATA
#undef SERIALIZATION_SAVE_DATA
#undef SERIALIZATION_SAVE_LOAD_DATA

#undef SERIALIZATION_TYPE_REGISTRY
#undef SERIALIZATION_CONDITIONAL_TYPE_REGISTRY

#undef SERIALIZATION_ARCHIVE
#undef _SERIALIZATION_ARCHIVE_EXPORT_TRAIT_KEY
#undef _SERIALIZATION_ARCHIVE_EXPORT_TYPE_TRAIT
#undef SERIALIZATION_ARCHIVE_EXPORT

#undef _DYNAMIC_SAVE_LOAD_IMPORT
#undef _DYNAMIC_SAVE_LOAD_DECLARATION
#undef _DYNAMIC_SAVE_LOAD_IMPLEMENTATION_WITH
#undef _DYNAMIC_SAVE_LOAD_IMPLEMENTATION
#undef _DYNAMIC_SAVE_LOAD_TEMPLATE_IMPLEMENTATION

#undef _FACTORY_TABEL_UPDATER_DECLARATION
#undef _FACTORY_TABEL_UPDATER_IMPLEMENTATION_WITH
#undef _FACTORY_TABEL_UPDATER_IMPLEMENTATION
#undef _FACTORY_TABEL_UPDATER_TEMPLATE_IMPLEMENTATION

#undef _CLONEABLE_DECLARATION_WITHOUT_KEY
#undef _CLONEABLE_DECLARATION
#undef _CLONEABLE_TEMPLATE_DECLARATION
#undef _CLONEABLE_IMPLEMENTATION_WITH
#undef _CLONEABLE_IMPLEMENTATION
#undef _CLONEABLE_TEMPLATE_IMPLEMENTATION

#undef POLYMORPHIC_IMPORT
#undef SERIALIZABLE_POLYMORPHIC
#undef SERIALIZABLE_POLYMORPHIC_TEMPLATE
#undef POLYMORPHIC_EXPORT
#undef POLYMORPHIC_TEMPLATE_EXPORT
#undef SERIALIZATION_POLYMORPHIC
#undef POLYMORPHIC
#undef POLYMORPHIC_TEMPLATE

#undef _SERIALIZATION_DECLARATION_IF
#undef _SERIALIZATION_DECLARATION
#undef _SERIALIZATION_IMPLEMENTATION_IF
#undef _SERIALIZATION_IMPLEMENTATION
#undef SERIALIZATION_CONDITIONAL_SAVE
#undef SERIALIZATION_CONDITIONAL_LOAD
#undef SERIALIZATION_CONDITIONAL_SAVE_LOAD
#undef SERIALIZATION_SAVE
#undef SERIALIZATION_LOAD
#undef SERIALIZATION_SAVE_LOAD
#undef SERIALIZATION
#undef SERIALIZATION_CONDITIONAL

#undef SIFAR_REQUIRE
#undef SIFAR_WHEN
