#ifndef EIGHTSER_DYNAMIC_INSTANTIABLE_TRAITS_HPP
#define EIGHTSER_DYNAMIC_INSTANTIABLE_TRAITS_HPP

#include <Eightser/Core/Hash.hpp>

#define INSTANTIABLE(...) \
        static inline bool autogenerated = ::eightser::dynamic::instantiable_registry.fixture<__VA_ARGS__>();

#define INSTANTIABLE_KEY(instantiable_key, ...) \
        static ::xxeightser_instantiable_traits_key_type key() { return instantiable_key; } \
        INSTANTIABLE(__VA_ARGS__)

using xxeightser_instantiable_traits_key_type = std::uint64_t;
static constexpr auto xxeightser_instantiable_traits_base_key = xxeightser_instantiable_traits_key_type(-1);

#endif // EIGHTSER_DYNAMIC_INSTANTIABLE_TRAITS_HPP
