// If you want to undef all external users macros
// you should include given file only after library files
// clean up
#undef SERIALIZATION_LOAD
#undef SERIALIZATION_SAVE
#undef SERIALIZATION_UNIFIED

#undef SERIALIZATION_ARCHIVE_ACCESS

#undef SERIALIZATION_READ_ARCHIVE_GENERIC
#undef SERIALIZATION_WRITE_ARCHIVE_GENERIC

#undef SERIALIZATION_CLASS_INFO
#undef SERIALIZATION_CLASS_TPL_INFO

#undef SERIALIZATION_CLASS_HASH_INFO
#undef SERIALIZATION_CLASS_TPL_HASH_INFO

#undef SERIALIZATION_TYPE_REGISTRY
#undef SERIALIZATION_TYPE_REGISTRY_IF
