// If you want to undef all external users macros
// you should include given file only after library files
// clean up
#undef SERIALIZATION_LOAD
#undef SERIALIZATION_SAVE
#undef SERIALIZATION_UNIFIED

#undef SERIALIZATION_ARCHIVE_ACCESS

#undef SERIALIZATION_READ_ARCHIVE_GENERIC
#undef SERIALIZATION_WRITE_ARCHIVE_GENERIC

#undef SERIALIZATION_IMPLEMENT_CLASS_INFO
#undef SERIALIZATION_IMPLEMENT_CLASS_TPL_INFO
