// If you want to undef all external lib's macros
// you should include given file only after library files
// note that: MACRO - is public macro, _MACRO - is private

// clean up
#undef SERIALIZATION_ACCESS

#undef SERIALIZATION_ARCHIVE
#undef EXPORT_SERIALIZATION_ARCHIVE

#undef CLONEABLE_BODY
#undef CLONEABLE

#undef POLYMORPHIC_BODY
#undef POLYMORPHIC

#undef SRIALIZABLE

#undef EXPORT_POLYMORPHIC_KEY
#undef EXPORT_POLYMORPHIC

#undef EXTERN_CONDITIONAL_SERIALIZATION
#undef EXTERN_SERIALIZATION

#undef CONDITIONAL_SERIALIZATION
#undef SERIALIZATION

#undef CONDITIONAL_TYPE_REGISTRY
#undef TYPE_REGISTRY

#undef SIRAF_STATIC_HASH
#undef SIRAF_STATIC_HASH_KEY_TYPE
#undef SIRAF_MAX_TEMPLATE_DEPTH
#undef SIRAF_ARCHIVE_MAX_TRAIT_KEY

#undef SIRAF_DEFAULT_DISABLE
#undef SIRAF_SMART_DISABLE

#undef SIRAF_SMART

#undef SIREQUIRE
#undef SIWHEN
#undef SIWITH
