// If you want to undef all external lib's macros
// you should include given file only after library files
// note that: MACRO - is public macro, _MACRO - is private

// clean up
#undef SERIALIZATION_ACCESS

#undef SERIALIZATION_ARCHIVE
#undef EXPORT_SERIALIZATION_ARCHIVE

#undef _CLONEABLE_TRAIT_IMPLEMENTATION
#undef _CLONEABLE_INTERFACE_IMPLEMENTATION
#undef _CLONEABLE_IMPLEMENTATION
#undef CLONEABLE_BODY
#undef CLONEABLE

#undef _POLYMORPHIC_ALIASE_IMPLEMENTATION
#undef _POLYMORPHIC_INTERFACE_IMPLEMENTATION
#undef _POLYMORPHIC_IMPLEMENTATION
#undef POLYMORPHIC_BODY
#undef POLYMORPHIC

#undef SRIALIZABLE

#undef EXPORT_POLYMORPHIC_KEY
#undef EXPORT_POLYMORPHIC

#undef EXTERN_CONDITIONAL_SERIALIZATION
#undef EXTERN_SERIALIZATION

#undef CONDITIONAL_SERIALIZATION
#undef SERIALIZATION

#undef CONDITIONAL_TYPE_REGISTRY
#undef TYPE_REGISTRY

#undef SIRAF_STATIC_HASH
#undef SIRAF_STATIC_HASH_KEY_TYPE
#undef SIRAF_MAX_TEMPLATE_DEPTH
#undef SIRAF_ARCHIVE_MAX_TRAIT_KEY

#undef SIRAF_DEFAULT_DISABLE
#undef SIRAF_SMART_DISABLE

#undef SIRAF_SMART

#undef STATIC_MESSAGE_UNREGISTERED_TYPE

#undef SIREQUIRE
#undef SIWHEN
#undef SIWITH
