// If you want to undef all external lib's macros
// you should include given file only after library files
// note that: MACRO - is public macro, _MACRO - is private

// clean up
#undef SERIALIZABLE_ACCESS

#undef SERIALIZATION_ARCHIVE
#undef EXPORT_SERIALIZATION_ARCHIVE

#undef _CLONEABLE_KEY_CALL
#undef _CLONEABLE_KEY_IMPLEMENTATION
#undef _CLONEABLE_FACTORY_TABLE_IMPLEMENTATION
#undef _CLONEABLE_IMPLEMENTATION
#undef _CLONEABLE_BODY

#undef _DYNAMIC_SAVE_LOAD_ALIASES
#undef _POLYMORPHIC_ARCHIVE_CALL
#undef _DYNAMIC_SAVE_LOAD_IMPLEMENTATION
#undef POLYMORPHIC_BODY
#undef POLYMORPHIC

#undef EXPORT_POLYMORPHIC_KEY
#undef EXPORT_POLYMORPHIC

#undef CONDITIONAL_LOAD_SERIALIZABLE_TYPE
#undef LOAD_SERIALIZABLE_TYPE

#undef _SERIALIZATION_DECLARATION_IF
#undef _SERIALIZATION_DECLARATION
#undef _SERIALIZATION_IMPLEMENTATION_IF
#undef _SERIALIZATION_IMPLEMENTATION
#undef CONDITIONAL_SAVE_SERIALIZABLE
#undef CONDITIONAL_LOAD_SERIALIZABLE
#undef _SERIALIZATION_CALL
#undef CONDITIONAL_SAVE_LOAD_SERIALIZABLE
#undef SAVE_SERIALIZABLE
#undef LOAD_SERIALIZABLE
#undef SAVE_LOAD_SERIALIZABLE
#undef CONDITIONAL_SERIALIZATION
#undef SERIALIZATION

#undef CONDITIONAL_REGISTRY_SERIALIZABLE_TYPE
#undef REGISTRY_SERIALIZABLE_TYPE
#undef CONDITIONAL_REGISTRY_TYPE
#undef REGISTRY_TYPE

#undef CONDITIONAL_SAVE_LOAD_SERIALIZABLE_TYPE
#undef SAVE_LOAD_SERIALIZABLE_TYPE

#undef CONDITIONAL_SAVE_SERIALIZABLE_TYPE
#undef SAVE_SERIALIZABLE_TYPE

#undef SIRAF_STATIC_HASH
#undef SIRAF_STATIC_HASH_KEY_TYPE
#undef SIRAF_MAX_TEMPLATE_DEPTH
#undef SIRAF_ARCHIVE_MAX_TRAIT_KEY

#undef SIRAF_SMART

#undef SIREQUIRE
#undef SIWHEN
#undef SIWITH
